name: Black Code Formatting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  black:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        
    - name: Check Black formatting
      run: |
        black --check --diff . 